### ISSUE TITLE
pvr clone clobbers ${S}  

### ISSUE THREAD

**Issue by KobusG** [pantavisor/meta-pantavisor#4]
In the **pvrexport** class, the **do_compile** step runs pvr clone, which seems to delete the contents of the pvrexport folder (${S}). 
This causes a continuity error if anything about the pv-container recipe is changed, as Yocto expects the output of do_unpack to be fine if the  SRC_URI or REV hasn't changed, only do-compile needs to be rerun.

**Comment by asac** [comment]
after another few iteration of yocto pain (seems it deletes $S if $s is changed from workdir (ouch); I think now its good. check how the subdir= of the SRC_URI's of the pvr export tarballs looks like now and adjust yours accordingly. couldnt find a better way but seems it works not also incrementally after changing do_compile code or do_deploy code

**Comment by KobusG** [comment]
Seems to be working, thanks.
