### ISSUE TITLE
pvrexport deploy

### ISSUE THREAD

**Issue by KobusG** [pantavisor/meta-pantavisor#5]
pvrexport do_deploy writes directly to ${DEPLOY_DIR_IMAGE}. It would be better if this and any similar recipes inherit deploy.bbclass and make use of ${DEPLOYDIR} instead. This allows use of setscene rebuilds, and avoids accidentally reusing old artifacts if the recipe needs to be rebuilt. 
Also try to make this work without fakeroot.

recipes using **pvr** commands also seem to pollute the host machine users' ~/.pvr/ dir. This is troublesome. Yocto recipe actions should ideally be isolated to the yocto build folder.
More of an issue is that recipes fail if **pvr init** hasn't been run on the host. This is an issue for containerised builds and CI builds.

**Comment by asac** [comment]
i fixed pvrexport.bbclass to use PVR_CONFIG_DIR rather than the global

i fixed DEPLOYDIR approach - thx

I completely redid how i do comple and deploy in pvrexport.bbclass.

Check if things are good for you now....

**Comment by KobusG** [comment]
it works, thanks.
